import {
  User,
  Provider,
  Appointment,
  ServiceCategoryInfo,
} from "@/types";

export const MOCK_DELAY = 800; // ms

export const mockDelay = (ms = MOCK_DELAY) =>
  new Promise((resolve) => setTimeout(resolve, ms));

export const SERVICE_CATEGORIES: ServiceCategoryInfo[] = [
  {
    id: "barber",
    label: "Barbearia",
    icon: "✂️",
    description: "Corte, barba e bigode",
    color: "#d97706",
  },
  {
    id: "hairdresser",
    label: "Cabeleireiro",
    icon: "💇",
    description: "Corte, tintura e tratamento",
    color: "#7c3aed",
  },
  {
    id: "manicure",
    label: "Manicure",
    icon: "💅",
    description: "Unhas das mãos",
    color: "#db2777",
  },
  {
    id: "pedicure",
    label: "Pedicure",
    icon: "🦶",
    description: "Unhas dos pés",
    color: "#dc2626",
  },
  {
    id: "makeup",
    label: "Maquiagem",
    icon: "💄",
    description: "Maquiagem artística e social",
    color: "#be185d",
  },
  {
    id: "massage",
    label: "Massagem",
    icon: "🪷",
    description: "Relaxante e terapêutica",
    color: "#059669",
  },
  {
    id: "aesthetics",
    label: "Estética",
    icon: "✨",
    description: "Limpeza de pele e tratamentos",
    color: "#0284c7",
  },
  {
    id: "other",
    label: "Outros",
    icon: "🌟",
    description: "Mais serviços",
    color: "#6b7280",
  },
];

export const mockUsers: Record<string, User> = {
  client1: {
    id: "client1",
    name: "João Silva",
    email: "joao@email.com",
    phone: "(73) 99999-0001",
    role: "client",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=joao",
    createdAt: "2024-01-15T10:00:00Z",
  },
  provider1: {
    id: "provider1",
    name: "Carlos Barbeiro",
    email: "carlos@email.com",
    phone: "(73) 99999-0002",
    role: "provider",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=carlos",
    createdAt: "2023-06-10T10:00:00Z",
  },
};

export const mockProviders: Provider[] = [
  {
    id: "prov1",
    userId: "provider1",
    name: "Barbearia do Carlos",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=barbearia",
    category: "barber",
    rating: 4.9,
    reviewCount: 128,
    address: "Rua das Flores, 45 - Centro, Ilhéus-BA",
    distance: 0.8,
    bio: "Há 15 anos oferecendo o melhor em cortes masculinos. Especialista em degradê e barba.",
    isAvailableNow: true,
    services: [
      { id: "s1", name: "Corte Social", description: "Corte clássico e elegante", price: 35, duration: 30, category: "barber", providerId: "prov1" },
      { id: "s2", name: "Corte + Barba", description: "Combo completo", price: 55, duration: 50, category: "barber", providerId: "prov1" },
      { id: "s3", name: "Degradê", description: "Degradê moderno", price: 40, duration: 40, category: "barber", providerId: "prov1" },
      { id: "s4", name: "Barba Completa", description: "Modelagem e hidratação", price: 30, duration: 30, category: "barber", providerId: "prov1" },
    ],
    workingHours: {
      mon: { open: "08:00", close: "19:00", closed: false },
      tue: { open: "08:00", close: "19:00", closed: false },
      wed: { open: "08:00", close: "19:00", closed: false },
      thu: { open: "08:00", close: "19:00", closed: false },
      fri: { open: "08:00", close: "19:00", closed: false },
      sat: { open: "08:00", close: "17:00", closed: false },
      sun: { open: "00:00", close: "00:00", closed: true },
    },
  },
  {
    id: "prov2",
    userId: "provider2",
    name: "Studio Ana Lima",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=ana",
    category: "hairdresser",
    rating: 4.8,
    reviewCount: 94,
    address: "Av. Soares Lopes, 210 - Pontal, Ilhéus-BA",
    distance: 1.4,
    bio: "Especialista em coloração e tratamentos capilares. Transforme seus cabelos!",
    isAvailableNow: true,
    services: [
      { id: "s5", name: "Corte Feminino", description: "Corte personalizado", price: 60, duration: 60, category: "hairdresser", providerId: "prov2" },
      { id: "s6", name: "Escova Progressiva", description: "Alisar e hidratar", price: 180, duration: 180, category: "hairdresser", providerId: "prov2" },
      { id: "s7", name: "Coloração", description: "Tintura completa", price: 120, duration: 120, category: "hairdresser", providerId: "prov2" },
      { id: "s8", name: "Hidratação", description: "Máscara e finalização", price: 55, duration: 45, category: "hairdresser", providerId: "prov2" },
    ],
    workingHours: {
      mon: { open: "09:00", close: "18:00", closed: false },
      tue: { open: "09:00", close: "18:00", closed: false },
      wed: { open: "09:00", close: "18:00", closed: false },
      thu: { open: "09:00", close: "18:00", closed: false },
      fri: { open: "09:00", close: "18:00", closed: false },
      sat: { open: "09:00", close: "15:00", closed: false },
      sun: { open: "00:00", close: "00:00", closed: true },
    },
  },
  {
    id: "prov3",
    userId: "provider3",
    name: "Espaço Bella Nails",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bella",
    category: "manicure",
    rating: 4.7,
    reviewCount: 67,
    address: "Rua Coronel Paiva, 88 - Malhado, Ilhéus-BA",
    distance: 2.1,
    bio: "Unhas perfeitas para cada ocasião. Gel, acrigel e nail art sob encomenda.",
    isAvailableNow: false,
    services: [
      { id: "s9", name: "Manicure Simples", description: "Esmaltação comum", price: 25, duration: 45, category: "manicure", providerId: "prov3" },
      { id: "s10", name: "Manicure + Pedicure", description: "Combo mãos e pés", price: 55, duration: 90, category: "manicure", providerId: "prov3" },
      { id: "s11", name: "Gel nas Unhas", description: "Aplicação de gel", price: 80, duration: 75, category: "manicure", providerId: "prov3" },
      { id: "s12", name: "Nail Art", description: "Arte personalizada", price: 50, duration: 60, category: "manicure", providerId: "prov3" },
    ],
    workingHours: {
      mon: { open: "09:00", close: "19:00", closed: false },
      tue: { open: "09:00", close: "19:00", closed: false },
      wed: { open: "09:00", close: "19:00", closed: false },
      thu: { open: "09:00", close: "19:00", closed: false },
      fri: { open: "09:00", close: "19:00", closed: false },
      sat: { open: "09:00", close: "17:00", closed: false },
      sun: { open: "00:00", close: "00:00", closed: true },
    },
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "apt1",
    clientId: "client1",
    providerId: "prov1",
    serviceId: "s2",
    date: "2025-07-28",
    time: "10:00",
    status: "confirmed",
    service: mockProviders[0].services[1],
    provider: mockProviders[0],
    notes: "",
    createdAt: "2025-07-25T09:30:00Z",
  },
  {
    id: "apt2",
    clientId: "client1",
    providerId: "prov2",
    serviceId: "s7",
    date: "2025-07-30",
    time: "14:00",
    status: "pending",
    service: mockProviders[1].services[2],
    provider: mockProviders[1],
    notes: "Quero clarear dois tons",
    createdAt: "2025-07-26T11:00:00Z",
  },
  {
    id: "apt3",
    clientId: "client1",
    providerId: "prov3",
    serviceId: "s10",
    date: "2025-07-20",
    time: "15:30",
    status: "completed",
    service: mockProviders[2].services[1],
    provider: mockProviders[2],
    notes: "",
    createdAt: "2025-07-18T10:00:00Z",
  },
];

// Provider mock appointments (incoming)
export const mockProviderAppointments: Appointment[] = [
  {
    id: "papt1",
    clientId: "client1",
    providerId: "prov1",
    serviceId: "s2",
    date: "2025-07-28",
    time: "10:00",
    status: "confirmed",
    service: mockProviders[0].services[1],
    client: mockUsers["client1"],
    notes: "",
    createdAt: "2025-07-25T09:30:00Z",
  },
  {
    id: "papt2",
    clientId: "client2",
    providerId: "prov1",
    serviceId: "s3",
    date: "2025-07-28",
    time: "11:00",
    status: "pending",
    service: mockProviders[0].services[2],
    client: { ...mockUsers["client1"], id: "client2", name: "Pedro Costa", email: "pedro@email.com" },
    notes: "Prefiro mais baixo na lateral",
    createdAt: "2025-07-26T14:00:00Z",
  },
];
